tasks:
- name: Gitpod Task
  before: |
    # Stores last segment of the Workspace Context URL in $path and trims spaces.
    # `gp info` prints information about the current Gitpod workspace.
    # `awk -F'/' '/Workspace Context URL/{print $NF}'` looks for the line containing 'Workspace Context URL' and prints the last field separated by "/".
    # `tr -d '[:space:]'` removes any leading or trailing whitespace from the path.
    echo "Retrieving the last part of the Workspace Context URL ..."
    path=$(gp info | awk -F'/' '/Workspace Context URL/{print $NF}' | tr -d '[:space:]')
    echo "Path '$path' is set."

    echo "npm build in $(pwd)"
    case "$path" in
      "checkout-example")
        echo "Build checkout-example application"
        cd checkout-example && npm install
      ;;
      "checkout-example-advanced")
        echo "Build checkout-example-advanced application"
        cd checkout-example-advanced && npm install
      ;;      
      "authorisation-adjustment-example")
        echo "Build authorisation-adjustment-example application"
        cd authorisation-adjustment-example && npm install
      ;;      
      "giftcard-example")
        echo "Build giftcard-example application"
        cd giftcard-example && npm install
      ;;
      "paybylink-example")
        echo "Build paybylink-example application"
        cd paybylink-example && npm install
      ;;
      "subscription-example")
        echo "Build subscription-example application"
        cd subscription-example && npm install
      ;;
      *)
        echo "Build default checkout-example application instead because '$path' is not defined ..."
        cd checkout-example && npm install
      ;;
    esac
    
    echo "npm install done."

  command: |
    # Check if environment variables are set in https://gitpod.io/variables.
    echo "Checking if environment variables are set ..."

    if [ -z ${ADYEN_HMAC_KEY+x} ] || [[ -z ${ADYEN_API_KEY+x} ]] || [[ -z ${ADYEN_CLIENT_KEY+x} ]] || [[ -z ${ADYEN_MERCHANT_ACCOUNT+x} ]]; then
      echo "Expected environment variables not found. Please set the ADYEN_HMAC_KEY, ADYEN_API_KEY, ADYEN_CLIENT_KEY, ADYEN_MERCHANT_ACCOUNT environment variables and rerun session https://gitpod.io/variables."
      exit 1
    fi

    # Run the application based on specified $path.
    echo "Starting application for '$path' in $(pwd)"
    npm run dev
    
# exposed ports
ports:
- port: 8080
  onOpen: open-preview
  visibility: public

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
