name: E2E Giftcard 

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'giftcard-example/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'giftcard-example/**'

jobs:
  giftcard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout giftcard-example
        uses: actions/checkout@v4
      - name: Build giftcard-example image
        run: docker build -t giftcard-example-image:latest giftcard-example
      - name: Start giftcard-example container
        run: docker run --rm -d --name giftcard-example-image -p 8080:8080 -e ADYEN_API_KEY="${{ secrets.ADYEN_API_KEY }}" -e ADYEN_MERCHANT_ACCOUNT=${{ secrets.ADYEN_MERCHANT_ACCOUNT }} -e ADYEN_CLIENT_KEY=${{ secrets.ADYEN_CLIENT_KEY }} -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} giftcard-example-image:latest
      - name: Run testing suite against giftcard-example
        run: docker run --rm --name adyen-testing-suite -e PLAYWRIGHT_FOLDERNAME=giftcard -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} --network host ghcr.io/adyen-examples/adyen-testing-suite:main
