name: E2E PayByLink 

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'paybylink-example/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'paybylink-example/**'

jobs:
  paybylink:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout paybylink-example
        uses: actions/checkout@v3
      - name: Build paybylink-example image
        run: docker build -t paybylink-example-image:latest paybylink-example
      - name: Start paybylink-example container
        run: docker run --rm -d --name paybylink-example-image -p 8080:8080 -e ADYEN_API_KEY="${{ secrets.ADYEN_API_KEY }}" -e ADYEN_MERCHANT_ACCOUNT=${{ secrets.ADYEN_MERCHANT_ACCOUNT }} -e ADYEN_CLIENT_KEY=${{ secrets.ADYEN_CLIENT_KEY }} -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} paybylink-example-image:latest
      - name: Run testing suite against paybylink-example
        run: docker run --rm --name adyen-testing-suite -e PLAYWRIGHT_FOLDERNAME=paybylink -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} --network host ghcr.io/adyen-examples/adyen-testing-suite:main
