name: E2E Subscription 

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'subscription-example/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'subscription-example/**'

jobs:
  subscription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout subscription-example
        uses: actions/checkout@v3
      - name: Build subscription-example image
        run: docker build -t subscription-example-image:latest subscription-example
      - name: Start subscription-example container
        run: docker run --rm -d --name subscription-example-image -p 8080:8080 -e ADYEN_API_KEY="${{ secrets.ADYEN_API_KEY }}" -e ADYEN_MERCHANT_ACCOUNT=${{ secrets.ADYEN_MERCHANT_ACCOUNT }} -e ADYEN_CLIENT_KEY=${{ secrets.ADYEN_CLIENT_KEY }} -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} subscription-example-image:latest
      - name: Run testing suite against subscription-example
        run: docker run --rm --name adyen-testing-suite -e PLAYWRIGHT_FOLDERNAME=subscription -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} --network host ghcr.io/adyen-examples/adyen-testing-suite:main
